const en = {
  'auth.title': 'Save your results',
  'auth.email': 'Email address',
  'auth.magic': 'Send magic link',
  'auth.checkEmail': 'Check your inbox and click the link to sign in.',
  'auth.signedIn': 'Signed in as',
  'auth.signOut': 'Sign out',
  'auth.syncHint': 'Optional: sign in only if you want to save results and come back later.',
  'auth.optionalHint': 'Optional. You can use the checker without logging in.',
  'nav.brandTitle': 'Tenant Rights',
  'nav.brandSub': 'Plain answers for renters',
  'nav.new': 'Start a new check',
  'nav.history': 'Saved results',
  'nav.learn': 'Help',
  'nav.guide': 'Renter basics',
  'nav.privacy': 'Privacy and API key safety',
  'nav.why': 'What this tool does',
  'nav.noSaved': 'No saved results yet. Sign in if you want to save them.',
  'nav.settings': 'Settings',
  'nav.keyCookie': 'Key active in this browser',
  'nav.addKey': 'Add your AI key',
  'nav.keyRequired': 'Required to run a check',
  'cloud.cloud': 'Synced',
  'top.connect': 'Start',
  'top.describe': 'Describe the problem',
  'top.jurisdiction': 'Location',
  'top.review': 'Review',
  'top.results': 'Results',
  'top.themeDark': 'Dark',
  'top.themeLight': 'Light',
  'loading.title': 'Loading',
  'loading.sub': 'Setting things up.',
  'err.prefix': 'Something went wrong:',
  's0.kicker': 'Free tenant rights checker',
  's0.title': 'Find out what your landlord can and cannot do.',
  's0.sub':
    'Tell us the problem in your own words. We check the tenant law for your location and give you a simple answer, a draft email, evidence to collect, and next steps.',
  's0.compareTitle': 'What you get',
  's0.b1': 'A plain answer based on your location.',
  's0.b2': 'A ready email, demand letter, and PDF.',
  's0.b3': 'Optional sign-in to save results for later.',
  's0.select': 'Use this model',
  's0.apiKey': 'Paste your AI API key',
  's0.keyHint': 'Your key is encrypted in a short-lived browser cookie and expires after 30 minutes.',
  's0.saveContinue': 'Start checking',
  's1.title': 'What happened?',
  's1.sub': 'Write it like you would text a friend. Add dates, money amounts, notices, photos, or messages if you have them.',
  's1.quick': 'Common questions',
  's1.continue': 'Next',
  's2.title': 'Where is the rental home?',
  's2.sub': 'Tenant laws change by location. Your state, province, or country is required. City is optional but helps find local help.',
  's2.region': 'State, province, or country',
  's2.regionPh': 'Start typing...',
  's2.city': 'City (optional)',
  's2.cityPh': 'e.g. San Francisco',
  's2.duration': 'How long have you lived there?',
  's2.back': 'Back',
  's2.next': 'Review',
  's3.title': 'Review before we check',
  's3.sub': 'Make sure the problem and location are right. Then run the check.',
  's3.dispute': 'Problem',
  's3.jurisdiction': 'Location',
  's3.duration': 'Time lived there',
  's3.keyNote': 'Your API key is used only for this request and stays out of the database.',
  's3.run': 'Run check',
  's3.back': 'Back',
  's3.running': 'Looking up the law',
  's3.runningSub': 'Checking tenant laws in {region}...',
  's4.verdictIllegal': 'Your landlord probably cannot do this',
  's4.verdictGrey': 'It depends. Read the details below',
  's4.verdictLegal': 'This is usually allowed',
  's4.lawCite': 'Law to double-check',
  's4.lawLink': 'Source link',
  's4.placeholderTitle': 'Replace placeholders before sending',
  's4.placeholderSub':
    'The email and letter may include [Your Name], [Address], or [Date]. Replace them with your real details first.',
  's4.emailTitle': 'Email you can send',
  's4.copyEmail': 'Copy',
  's4.optionsTitle': 'What you can do next',
  's4.demandTitle': 'Formal demand letter',
  's4.demandSub': 'A stronger letter you can print and send by certified mail.',
  's4.demandBtn': 'Write demand letter',
  's4.demandLoading': 'Writing...',
  's4.copyLetter': 'Copy',
  's4.orgsTitle': 'Free help near you ({region})',
  's4.orgsEmpty': 'No local resources found. Search online for tenant help in your area.',
  's4.lawyerTitle': 'When to talk to a lawyer',
  's4.pdfTitle': 'Save as PDF',
  's4.pdfSub': 'Download this page as a file you can print or share.',
  's4.pdfBtn': 'Download PDF',
  's4.another': 'Check another issue',
  'modal.guideTitle': 'Renter basics',
  'modal.close': 'Close',
  'modal.done': 'Got it',
  'modal.securityTitle': 'Privacy and API key safety',
  'modal.securityOk': 'Got it',
  'modal.whyTitle': 'What this tool does',
  'modal.settingsTitle': 'AI model and key',
  'modal.saveKey': 'Save key for 30 minutes',
  'modal.removeKey': 'Remove key from this browser',
  'modal.connected': 'Connected to {provider}. Key ending in {hint}',
  'modal.provider': 'Pick an AI model',
  'modal.keyLabel': 'Your API key',
  'modal.keyHelp': 'The key is encrypted in a short-lived httpOnly cookie. It is never saved to Supabase.',
  'pdf.downloaded': 'PDF saved. Fill in placeholders before using it.',
  'pdf.error': 'Could not create the PDF. Try again or copy the sections by hand.',
  'val.situation': 'Please describe what your landlord is doing.',
  'val.detail': 'Please add a little more detail so we can find the right law.',
  'val.region': 'Please enter your state, province, or country.',
} as const;

export type MessageKey = keyof typeof en;

export function t(key: MessageKey, vars?: Record<string, string>): string {
  let value: string = en[key] ?? key;
  if (vars) {
    for (const [name, replacement] of Object.entries(vars)) {
      value = value.replaceAll(`{${name}}`, replacement);
    }
  }
  return value;
}
